name: SofraApp
options:
  bundleIdPrefix: com.albayt.sofra
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  defaultConfig: Release
  createIntermediateGroups: true
  generateEmptyDirectories: true
  groupSortPosition: top

configs:
  Debug: debug
  Release: release

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "Apple Development"
    INFOPLIST_FILE: SofraApp/Resources/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    SUPPORTED_PLATFORMS: iphoneos iphonesimulator

targets:
  SofraApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SofraApp/Sources
        type: group
    resources:
      - path: SofraApp/Resources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.albayt.sofra
        INFOPLIST_FILE: SofraApp/Resources/Info.plist
        DEVELOPMENT_ASSET_PATHS: ""
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          SWIFT_OPTIMIZATION_LEVEL: -Onone
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
    info:
      path: SofraApp/Resources/Info.plist
      properties:
        CFBundleDevelopmentRegion: ar
        CFBundleDisplayName: سفرة البيت
        CFBundleName: SofraApp
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIUserInterfaceStyle: Light
        ITSAppUsesNonExemptEncryption: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
